apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: probe-liveness-readiness-tcp
    image: k8s.gcr.io/nginx
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 90
      periodSeconds: 10
   
