  
apiVersion: v1
kind: Pod
metadata:
  name: start
spec:
  containers:
  - name: probe-liveness-startup-http
    image: k8s.gcr.io/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      failureThreshold: 1
      periodSeconds: 30
    startupProbe:
      httpGet:
        path: /healthz
        port: 8080
      failureThreshold: 90
      periodSeconds: 10
